# Generated by Django 4.2.1 on 2023-06-23 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("crm_software", "0005_auto_20230610_2304"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="sales_team",
            new_name="sales_member",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="sales_team",
            new_name="sales_member",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="type",
            new_name="attendees",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="client",
            new_name="customer",
        ),
        migrations.RemoveField(
            model_name="events",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="events",
            name="price",
        ),
        migrations.AddField(
            model_name="contract",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_status",
            field=models.CharField(
                choices=[("On_Going", "On Going"), ("Finished", "Finished")],
                default="On_Going",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="support_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
